[project]
name = "ollama2gym"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aleksandr Loktionov", email = "loktionov129@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "black>=26.5.1",
    "mypy>=2.3.1",
    "pylint>=4.0.9",
    "ruff>=0.16.9",
]

[project.scripts]
ollama2gym = "ollama2gym:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
